name: test
on:
  push:
    tags-ignore:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run unit tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Setup .npmrc file for NPM registry
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: yarn
      - name: Check types
        run: yarn typecheck
      - name: Lint
        run: yarn lint
      - name: Unit tests
        run: yarn test:ci
      - name: '@grafana/create-plugin - test an app plugin generation'
        run: yarn workspace @grafana/create-plugin run generate-app && (cd ./packages/create-plugin/generated && yarn && yarn build && yarn lint)
      - name: '@grafana/create-plugin - test panel plugin generation'
        run: yarn workspace @grafana/create-plugin run generate-panel && (cd ./packages/create-plugin/generated && yarn && yarn build && yarn lint)
      - name: '@grafana/create-plugin - test datasource plugin generation'
        run: yarn workspace @grafana/create-plugin run generate-datasource && (cd ./packages/create-plugin/generated && yarn && yarn build && yarn lint)
