name: test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run unit tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Setup .npmrc file for NPM registry
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: yarn
      - name: Check types
        run: yarn typecheck
      - name: Lint
        run: yarn lint
      - name: Unit tests
        run: yarn jest
      - name: test an app plugin generation
        run: yarn generate-app && (cd generated && yarn && yarn build && yarn lint)
      - name: test panel plugin generation
        run: yarn generate-panel && (cd generated && yarn && yarn build && yarn lint)
      - name: test datasource plugin generation
        run: yarn generate-datasource && (cd generated && yarn && yarn build && yarn lint)
